"""harden integrity: composite FK chain + utc time guard

Revision ID: 335b7e83d38f
Revises: 74bc5654395d
Create Date: 2026-09-17 21:14:25.816461

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "335b7e83d38f"
down_revision: str | None = "74bc5654395d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # ⚠️ 手工补充说明（不是 autogenerate 生成的）：
    # Alembic 的 autogenerate **不会检测 CHECK 约束的新增/删除**，本次新增的 4 个
    # 时间格式 CHECK 全部被静默漏掉了（模型里有、迁移里没有，且没有任何提示）。
    # 已用 test_migration_schema.py 做永久性比对，这类偏差以后会被测试直接抓住。
    # 详见 backend/README.md「已知坑」。
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_chapters_id_material", ["id", "material_id"])

    with op.batch_alter_table("knowledge_points", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            existing_nullable=False,
        )
        batch_op.create_index("idx_kp_chapter", ["chapter_id"], unique=False)
        batch_op.create_index("idx_kp_material", ["material_id"], unique=False)
        batch_op.drop_constraint(
            batch_op.f("fk_knowledge_points_material_id_materials"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_knowledge_points_section_id_sections"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_knowledge_points_chapter_id_chapters"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_kp_section_chain",
            "sections",
            ["section_id", "chapter_id", "material_id"],
            ["id", "chapter_id", "material_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_knowledge_points_created_at_utc_iso"),
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
        )

    with op.batch_alter_table("kp_prerequisites", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            existing_nullable=False,
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_kp_prerequisites_created_at_utc_iso"),
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
        )

    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            existing_nullable=False,
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_materials_created_at_utc_iso"),
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_materials_updated_at_utc_iso"),
            "updated_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', updated_at)",
        )

    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index("idx_sections_material", ["material_id"], unique=False)
        batch_op.create_unique_constraint("uq_sections_chain", ["id", "chapter_id", "material_id"])
        batch_op.drop_constraint(
            batch_op.f("fk_sections_material_id_materials"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("fk_sections_chapter_id_chapters"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_sections_chapter_chain",
            "chapters",
            ["chapter_id", "material_id"],
            ["id", "material_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 同样手工补上 CHECK 约束的删除（autogenerate 不会处理 CHECK 的增删）
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sections_chapter_chain", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_sections_chapter_id_chapters"),
            "chapters",
            ["chapter_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_sections_material_id_materials"),
            "materials",
            ["material_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint("uq_sections_chain", type_="unique")
        batch_op.drop_index("idx_sections_material")

    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_materials_updated_at_utc_iso"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_materials_created_at_utc_iso"), type_="check")
        batch_op.alter_column(
            "updated_at", existing_type=sa.TEXT(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.TEXT(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("kp_prerequisites", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_kp_prerequisites_created_at_utc_iso"), type_="check"
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.TEXT(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("knowledge_points", schema=None) as batch_op:
        batch_op.drop_constraint("fk_kp_section_chain", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_knowledge_points_chapter_id_chapters"),
            "chapters",
            ["chapter_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_knowledge_points_section_id_sections"),
            "sections",
            ["section_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_knowledge_points_material_id_materials"),
            "materials",
            ["material_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index("idx_kp_material")
        batch_op.drop_index("idx_kp_chapter")
        batch_op.drop_constraint(
            batch_op.f("ck_knowledge_points_created_at_utc_iso"), type_="check"
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.TEXT(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_constraint("uq_chapters_id_material", type_="unique")

    # ### end Alembic commands ###
