"""core tables: materials blocks outline kp edges

Revision ID: 74bc5654395d
Revises:
Create Date: 2026-09-17 20:40:06.828995

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "74bc5654395d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("parse_method", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("uncertain_notes", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "parse_method IS NULL OR parse_method IN ('text_extract', 'multimodal_llm', 'ocr', 'asr')",
            name=op.f("ck_materials_parse_method"),
        ),
        sa.CheckConstraint(
            "source_type IN ('pdf_text', 'pdf_scan', 'docx', 'pptx', 'image', 'audio')",
            name=op.f("ck_materials_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'parsing', 'done', 'failed', 'partial')",
            name=op.f("ck_materials_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("file_hash", name=op.f("uq_materials_file_hash")),
    )
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.create_index("idx_materials_created", ["created_at"], unique=False)
        batch_op.create_index("idx_materials_status", ["status"], unique=False)

    op.create_table(
        "material_blocks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("ts_start_ms", sa.Integer(), nullable=True),
        sa.Column("ts_end_ms", sa.Integer(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("block_type", sa.Text(), nullable=False),
        sa.Column("heading_level", sa.Integer(), nullable=True),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column("image_path", sa.Text(), nullable=True),
        sa.Column("bbox", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "block_type IN ('heading', 'paragraph', 'table', 'code', 'formula', 'image_caption', 'question', 'other')",
            name=op.f("ck_material_blocks_block_type"),
        ),
        sa.CheckConstraint(
            "heading_level IS NULL OR (heading_level BETWEEN 1 AND 6)",
            name=op.f("ck_material_blocks_heading_level_range"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_material_blocks_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_blocks_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_blocks")),
        sa.UniqueConstraint("material_id", "seq", name="uq_blocks_material_seq"),
    )
    with op.batch_alter_table("material_blocks", schema=None) as batch_op:
        batch_op.create_index("idx_blocks_material_seq", ["material_id", "seq"], unique=False)

    op.create_table(
        "chapters",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("number", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("summary_md", sa.Text(), nullable=True),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_chapters_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_chapters_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["material_blocks.id"],
            name=op.f("fk_chapters_source_block_id_material_blocks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint("material_id", "seq", name="uq_chapters_material_seq"),
    )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_index("idx_chapters_material_seq", ["material_id", "seq"], unique=False)

    op.create_table(
        "sections",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("chapter_id", sa.Text(), nullable=False),
        sa.Column("number", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("summary_md", sa.Text(), nullable=True),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_sections_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_sections_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_sections_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["material_blocks.id"],
            name=op.f("fk_sections_source_block_id_material_blocks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("chapter_id", "seq", name="uq_sections_chapter_seq"),
    )
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index("idx_sections_chapter_seq", ["chapter_id", "seq"], unique=False)

    op.create_table(
        "knowledge_points",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("section_id", sa.Text(), nullable=False),
        sa.Column("chapter_id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("summary_md", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("difficulty_reason", sa.Text(), nullable=True),
        sa.Column("kp_type", sa.Text(), server_default=sa.text("'concept'"), nullable=False),
        sa.Column("source_material_id", sa.Text(), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kp_type IN ('concept', 'skill', 'theorem', 'method', 'fact')",
            name=op.f("ck_knowledge_points_kp_type"),
        ),
        sa.CheckConstraint(
            "difficulty BETWEEN 1 AND 5", name=op.f("ck_knowledge_points_difficulty_range")
        ),
        sa.CheckConstraint(
            "length(trim(source_quote)) > 0",
            name=op.f("ck_knowledge_points_source_quote_not_blank"),
        ),
        sa.CheckConstraint(
            "needs_review IN (0, 1)", name=op.f("ck_knowledge_points_needs_review_boolean")
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_knowledge_points_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_knowledge_points_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_knowledge_points_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_knowledge_points_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["material_blocks.id"],
            name=op.f("fk_knowledge_points_source_block_id_material_blocks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["materials.id"],
            name=op.f("fk_knowledge_points_source_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_points")),
        sa.UniqueConstraint("section_id", "name", name="uq_kp_section_name"),
    )
    with op.batch_alter_table("knowledge_points", schema=None) as batch_op:
        batch_op.create_index("idx_kp_difficulty", ["difficulty"], unique=False)
        batch_op.create_index("idx_kp_review", ["needs_review"], unique=False)
        batch_op.create_index("idx_kp_section", ["section_id", "seq"], unique=False)

    op.create_table(
        "kp_prerequisites",
        sa.Column("kp_id", sa.Text(), nullable=False),
        sa.Column("prereq_kp_id", sa.Text(), nullable=False),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column(
            "source_channel", sa.Text(), server_default=sa.text("'semantic'"), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("pruned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('hard', 'soft')", name=op.f("ck_kp_prerequisites_relation_type")
        ),
        sa.CheckConstraint(
            "source_channel IN ('structure', 'semantic', 'both')",
            name=op.f("ck_kp_prerequisites_source_channel"),
        ),
        sa.CheckConstraint("kp_id != prereq_kp_id", name=op.f("ck_kp_prerequisites_no_self_loop")),
        sa.CheckConstraint(
            "length(trim(reason)) > 0", name=op.f("ck_kp_prerequisites_reason_not_blank")
        ),
        sa.CheckConstraint(
            "needs_review IN (0, 1)", name=op.f("ck_kp_prerequisites_needs_review_boolean")
        ),
        sa.CheckConstraint("pruned IN (0, 1)", name=op.f("ck_kp_prerequisites_pruned_boolean")),
        sa.ForeignKeyConstraint(
            ["kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_kp_prerequisites_kp_id_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prereq_kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_kp_prerequisites_prereq_kp_id_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("kp_id", "prereq_kp_id", name=op.f("pk_kp_prerequisites")),
    )
    with op.batch_alter_table("kp_prerequisites", schema=None) as batch_op:
        batch_op.create_index("idx_edges_prereq", ["prereq_kp_id"], unique=False)
        batch_op.create_index("idx_edges_pruned", ["pruned"], unique=False)
        batch_op.create_index("idx_edges_review", ["needs_review"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kp_prerequisites", schema=None) as batch_op:
        batch_op.drop_index("idx_edges_review")
        batch_op.drop_index("idx_edges_pruned")
        batch_op.drop_index("idx_edges_prereq")

    op.drop_table("kp_prerequisites")
    with op.batch_alter_table("knowledge_points", schema=None) as batch_op:
        batch_op.drop_index("idx_kp_section")
        batch_op.drop_index("idx_kp_review")
        batch_op.drop_index("idx_kp_difficulty")

    op.drop_table("knowledge_points")
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_index("idx_sections_chapter_seq")

    op.drop_table("sections")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_index("idx_chapters_material_seq")

    op.drop_table("chapters")
    with op.batch_alter_table("material_blocks", schema=None) as batch_op:
        batch_op.drop_index("idx_blocks_material_seq")

    op.drop_table("material_blocks")
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_index("idx_materials_status")
        batch_op.drop_index("idx_materials_created")

    op.drop_table("materials")
    # ### end Alembic commands ###
