"""add remaining 8 tables: examples misconceptions embeddings questions qa jobs llm_calls

Revision ID: 1383d287b94e
Revises: 335b7e83d38f
Create Date: 2026-09-17 22:01:16.968305

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1383d287b94e"
down_revision: str | None = "335b7e83d38f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("stage_detail", sa.Text(), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
            name=op.f("ck_jobs_created_at_utc_iso"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', finished_at)",
            name=op.f("ck_jobs_finished_at_utc_iso"),
        ),
        sa.CheckConstraint(
            "job_type IN ('parse', 'extract_knowledge', 'embed', 'reindex')",
            name=op.f("ck_jobs_job_type"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR started_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', started_at)",
            name=op.f("ck_jobs_started_at_utc_iso"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_jobs_status")
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_jobs_progress_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("idx_jobs_created", ["created_at"], unique=False)
        batch_op.create_index("idx_jobs_status", ["status"], unique=False)
        batch_op.create_index("idx_jobs_target", ["target_id", "status"], unique=False)

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("caller", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("schema_valid", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
            name=op.f("ck_llm_calls_created_at_utc_iso"),
        ),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_llm_calls_retry_count_non_negative")),
        sa.CheckConstraint(
            "schema_valid IS NULL OR schema_valid IN (0, 1)",
            name=op.f("ck_llm_calls_schema_valid_boolean"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index("idx_llm_calls_caller", ["caller"], unique=False)
        batch_op.create_index("idx_llm_calls_created", ["created_at"], unique=False)

    op.create_table(
        "qa_sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("student_label", sa.Text(), nullable=True),
        sa.Column("material_scope", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
            name=op.f("ck_qa_sessions_created_at_utc_iso"),
        ),
        sa.CheckConstraint(
            "updated_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', updated_at)",
            name=op.f("ck_qa_sessions_updated_at_utc_iso"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_sessions")),
    )
    with op.batch_alter_table("qa_sessions", schema=None) as batch_op:
        batch_op.create_index("idx_qa_sessions_created", ["created_at"], unique=False)

    op.create_table(
        "qa_turns",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column("turn_type", sa.Text(), nullable=True),
        sa.Column("retrieved_kp_ids", sa.Text(), nullable=True),
        sa.Column("retrieved_block_ids", sa.Text(), nullable=True),
        sa.Column("grounded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("diagnosis_json", sa.Text(), nullable=True),
        sa.Column("llm_call_id", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
            name=op.f("ck_qa_turns_created_at_utc_iso"),
        ),
        sa.CheckConstraint("role IN ('student', 'tutor')", name=op.f("ck_qa_turns_role")),
        sa.CheckConstraint(
            "turn_type IS NULL OR turn_type IN ('probe', 'hint1', 'hint2', 'explain', 'confirm', 'refuse', 'student_answer', 'student_question')",
            name=op.f("ck_qa_turns_turn_type"),
        ),
        sa.CheckConstraint("grounded IN (0, 1)", name=op.f("ck_qa_turns_grounded_boolean")),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_qa_turns_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["llm_call_id"],
            ["llm_calls.id"],
            name=op.f("fk_qa_turns_llm_call_id_llm_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["qa_sessions.id"],
            name=op.f("fk_qa_turns_session_id_qa_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_turns")),
        sa.UniqueConstraint("session_id", "seq", name="uq_turns_session_seq"),
    )
    with op.batch_alter_table("qa_turns", schema=None) as batch_op:
        batch_op.create_index("idx_turns_grounded", ["grounded"], unique=False)
        batch_op.create_index("idx_turns_session", ["session_id", "seq"], unique=False)

    op.create_table(
        "kp_embeddings",
        sa.Column("kp_id", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("text_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%S+00:00','now'))"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "created_at IS strftime('%Y-%m-%dT%H:%M:%S+00:00', created_at)",
            name=op.f("ck_kp_embeddings_created_at_utc_iso"),
        ),
        sa.CheckConstraint(
            "dim = length(vector) / 4", name=op.f("ck_kp_embeddings_dim_matches_vector_length")
        ),
        sa.CheckConstraint("dim > 0", name=op.f("ck_kp_embeddings_dim_positive")),
        sa.ForeignKeyConstraint(
            ["kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_kp_embeddings_kp_id_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("kp_id", name=op.f("pk_kp_embeddings")),
    )
    op.create_table(
        "kp_examples",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kp_id", sa.Text(), nullable=False),
        sa.Column("question_type", sa.Text(), nullable=False),
        sa.Column("stem_md", sa.Text(), nullable=False),
        sa.Column("options_json", sa.Text(), nullable=True),
        sa.Column("answer_md", sa.Text(), nullable=False),
        sa.Column("analysis_md", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "question_type IN ('single_choice', 'multi_choice', 'fill_blank', 'short_answer', 'coding', 'true_false', 'other')",
            name=op.f("ck_kp_examples_question_type"),
        ),
        sa.CheckConstraint(
            "difficulty IS NULL OR difficulty BETWEEN 1 AND 5",
            name=op.f("ck_kp_examples_difficulty_range"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_kp_examples_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_kp_examples_kp_id_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["material_blocks.id"],
            name=op.f("fk_kp_examples_source_block_id_material_blocks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kp_examples")),
    )
    with op.batch_alter_table("kp_examples", schema=None) as batch_op:
        batch_op.create_index("idx_examples_kp", ["kp_id", "seq"], unique=False)

    op.create_table(
        "kp_misconceptions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kp_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cause", sa.Text(), nullable=True),
        sa.Column("remedy", sa.Text(), nullable=True),
        sa.Column("trigger_pattern", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "source IS NULL OR source IN ('material', 'llm_inferred', 'human')",
            name=op.f("ck_kp_misconceptions_source"),
        ),
        sa.ForeignKeyConstraint(
            ["kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_kp_misconceptions_kp_id_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kp_misconceptions")),
    )
    with op.batch_alter_table("kp_misconceptions", schema=None) as batch_op:
        batch_op.create_index("idx_misconceptions_kp", ["kp_id"], unique=False)
        batch_op.create_index("idx_misconceptions_source", ["source"], unique=False)

    op.create_table(
        "questions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("question_type", sa.Text(), nullable=False),
        sa.Column("stem_md", sa.Text(), nullable=False),
        sa.Column("options_json", sa.Text(), nullable=True),
        sa.Column("answer_md", sa.Text(), nullable=True),
        sa.Column("answer_missing", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("pk_kp_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "question_type IN ('single_choice', 'multi_choice', 'fill_blank', 'short_answer', 'coding', 'true_false', 'other')",
            name=op.f("ck_questions_question_type"),
        ),
        sa.CheckConstraint(
            "(answer_missing = 1 AND answer_md IS NULL) OR (answer_missing = 0 AND answer_md IS NOT NULL)",
            name=op.f("ck_questions_answer_missing_consistent"),
        ),
        sa.CheckConstraint(
            "answer_missing IN (0, 1)", name=op.f("ck_questions_answer_missing_boolean")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_questions_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pk_kp_id"],
            ["knowledge_points.id"],
            name=op.f("fk_questions_pk_kp_id_knowledge_points"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["material_blocks.id"],
            name=op.f("fk_questions_source_block_id_material_blocks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index("idx_questions_kp", ["pk_kp_id"], unique=False)
        batch_op.create_index("idx_questions_material", ["material_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ⚠️ 有数据的库上执行 downgrade 会**丢数据**（SQLite 的 DROP TABLE 不可逆）。
    #    仅限本地开发库使用，禁止对共享库 / 演示库执行。详见 backend/README.md。
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index("idx_questions_material")
        batch_op.drop_index("idx_questions_kp")

    op.drop_table("questions")
    with op.batch_alter_table("kp_misconceptions", schema=None) as batch_op:
        batch_op.drop_index("idx_misconceptions_source")
        batch_op.drop_index("idx_misconceptions_kp")

    op.drop_table("kp_misconceptions")
    with op.batch_alter_table("kp_examples", schema=None) as batch_op:
        batch_op.drop_index("idx_examples_kp")

    op.drop_table("kp_examples")
    op.drop_table("kp_embeddings")
    with op.batch_alter_table("qa_turns", schema=None) as batch_op:
        batch_op.drop_index("idx_turns_session")
        batch_op.drop_index("idx_turns_grounded")

    op.drop_table("qa_turns")
    with op.batch_alter_table("qa_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_qa_sessions_created")

    op.drop_table("qa_sessions")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index("idx_llm_calls_created")
        batch_op.drop_index("idx_llm_calls_caller")

    op.drop_table("llm_calls")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_jobs_target")
        batch_op.drop_index("idx_jobs_status")
        batch_op.drop_index("idx_jobs_created")

    op.drop_table("jobs")
    # ### end Alembic commands ###
